"""
Django settings for eBallot project.
Generated by 'django-admin startproject' using Django 5.2.1.
"""

from pathlib import Path
import os

DEMO_K_ANON = 10

BASE_DIR = Path(__file__).resolve().parent.parent

# --- Core dev settings ---
SECRET_KEY = "django-insecure-=0cxwz0qfc8p(@q3s$ncpw##118q*im#^f01$2tm+wy9bwes=t"
DEBUG = True
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# --- Email (SMTP μέσω Gmail) ---
# Χρησιμοποιούμε ΜΟΝΟ smtp backend. Βάλε App Password στο env ή άστο στο fallback για δοκιμή.
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "t.goulianos@gmail.com")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "mzutmfefnyvcnbmp")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER          # ΠΡΕΠΕΙ να ταιριάζει με το Gmail σου
CONTACT_EMAIL = os.environ.get("CONTACT_EMAIL", EMAIL_HOST_USER)
EMAIL_TIMEOUT = 20
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# --- Apps ---
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.sitemaps",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "core",
    "widget_tweaks",
]

# --- Middleware ---
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "eBallot.urls"

# --- Templates ---
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "eBallot.wsgi.application"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

# --- Database (SQLite for local dev) ---
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTH_USER_MODEL = "core.CustomUser"

# --- Password validation ---
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --- i18n / l10n ---
LANGUAGE_CODE = "en-us"
LANGUAGES = [
    ("en", "English"),
    ("el", "Greek"),
]
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True
LOCALE_PATHS = [BASE_DIR / "locale"]

# --- Static & media ---
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]  # αν δεν υπάρχει φάκελος, μπορείς να το αφαιρέσεις
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# --- Defaults ---
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
