"""
Django settings for eBallot project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import dj_database_url  # <-- add this
from pathlib import Path


DEMO_K_ANON = 10
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-=0cxwz0qfc8p(@q3s$ncpw##118q*im#^f01$2tm+wy9bwes=t"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# during local testing you probably want the console backend:
# ── EMAIL BACKEND ───────────────────────────────────────────────
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"  # Gmail example
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "t.goulianos@gmail.com"  # the address that sends
EMAIL_HOST_PASSWORD = "mzutmfefnyvcnbmp"  # Gmail App-Password *
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

CONTACT_EMAIL = EMAIL_HOST_USER
# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.sitemaps",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_extensions',
    "core",
    "widget_tweaks",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "eBallot.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'core' / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "eBallot.wsgi.application"

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTH_USER_MODEL = 'core.CustomUser'
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

LANGUAGES = [
    ('en', 'English'),
    ('el', 'Greek'),
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Heroku additions (non-destructive)
# --------------------------
import os
import dj_database_url  # already imported above; safe to import again

# 1) Override secrets & debug from environment (keeps your dev defaults above)
SECRET_KEY = os.environ.get("SECRET_KEY", SECRET_KEY)
DEBUG = os.environ.get("DEBUG", str(DEBUG)).lower() == "true"

# 2) Hosts & CSRF (set these in Heroku config vars)
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", ",".join(ALLOWED_HOSTS or [])).split(",") if ALLOWED_HOSTS is not None else ["*"]
CSRF_TRUSTED_ORIGINS = [
    os.environ.get("CSRF_TRUSTED_ORIGIN", "").strip()
] if os.environ.get("CSRF_TRUSTED_ORIGIN") else []

# 3) WhiteNoise for static files (insert into middleware without editing the list)
try:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
except Exception:
    # If MIDDLEWARE is not defined for some reason, skip
    pass

STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# 4) Database: keep sqlite locally, auto-swap to Postgres on Heroku via DATABASE_URL
DATABASES["default"] = dj_database_url.config(
    default=f"sqlite:///{DATABASES['default']['NAME']}",
    conn_max_age=600,
    ssl_require=bool(os.environ.get("DYNO")),  # True on Heroku dynos
)

# 5) Email via env (don’t hardcode secrets in code)
EMAIL_HOST = os.environ.get("EMAIL_HOST", EMAIL_HOST)
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", EMAIL_PORT))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", str(EMAIL_USE_TLS)).lower() == "true"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", EMAIL_HOST_USER)
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", EMAIL_HOST_PASSWORD)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", DEFAULT_FROM_EMAIL)
CONTACT_EMAIL = DEFAULT_FROM_EMAIL

# 6) Production security (only when DEBUG=False)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "True").lower() == "true"