# Generated by Django 5.2.1 on 2025-06-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_invitation_used_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age_group",
            field=models.CharField(
                choices=[
                    ("18-25", "18-25"),
                    ("26-35", "26-35"),
                    ("36-45", "36-45"),
                    ("46-60", "46-60"),
                    ("60+", "60+"),
                    ("Unknown", "Unknown"),
                ],
                default="Unknown",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Prefer not to say", "Prefer not to say"),
                    ("Unknown", "Unknown"),
                ],
                default="Unknown",
                max_length=20,
            ),
        ),
    ]
