# Generated by Django 5.1.2 on 2025-06-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_customuser_age_group_alter_customuser_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
