# Generated by Django 5.1.2 on 2025-06-25 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_vote_user_delete_voterecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemographicGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_group", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="vote",
            name="user",
        ),
        migrations.AddField(
            model_name="vote",
            name="demographic_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.demographicgroup",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="VoterLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voter_logs",
                        to="core.election",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voter_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "election")},
            },
        ),
    ]
