# Generated by Django 5.1.2 on 2025-06-25 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_demographicgroup_remove_vote_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="vote_hash",
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vote",
            name="demographic_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.demographicgroup",
            ),
        ),
    ]
