# Generated by Django 5.2.1 on 2025-06-30 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_vote_vote_hash_alter_vote_demographic_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elections_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
