# Generated by Django 5.2.1 on 2025-07-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_usergroup_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="vote_hash",
        ),
        migrations.RemoveField(
            model_name="voterlog",
            name="voted_at",
        ),
        migrations.AddField(
            model_name="voterlog",
            name="has_voted",
            field=models.BooleanField(default=False),
        ),
    ]
