# Generated by Django 5.2.1 on 2025-07-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_vote_vote_hash_remove_voterlog_voted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="max_choices",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Πόσες επιλογές επιτρέπονται σε κάθε ψηφοφόρο"
            ),
        ),
    ]
