# Generated by Django 5.2.1 on 2025-07-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_election_max_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="receipt_hash",
            field=models.CharField(
                default=1, editable=False, max_length=64, unique=True
            ),
            preserve_default=False,
        ),
    ]
