# Generated by Django 5.2.1 on 2025-08-06 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_vote_receipt_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='is_public',
        ),
        migrations.AddField(
            model_name='election',
            name='visibility',
            field=models.CharField(choices=[('public', 'Δημόσια - Ορατή χωρίς κωδικό'), ('private_visible', 'Ιδιωτική - Ορατή με κωδικό'), ('private_hidden', 'Αόρατη - Ιδιωτική')], default='public', max_length=20, verbose_name='Ορατότητα Εκλογής'),
        ),
        migrations.AlterField(
            model_name='election',
            name='active_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Έγινε Ενεργή Από'),
        ),
        migrations.AlterField(
            model_name='election',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργός'),
        ),
        migrations.AlterField(
            model_name='election',
            name='description',
            field=models.TextField(verbose_name='Περιγραφή'),
        ),
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(verbose_name='Ημερομηνία Λήξης'),
        ),
        migrations.AlterField(
            model_name='election',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='elections', to='core.usergroup', verbose_name='Ομάδες Ψηφοφόρων'),
        ),
        migrations.AlterField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Ενεργή'),
        ),
        migrations.AlterField(
            model_name='election',
            name='max_choices',
            field=models.PositiveSmallIntegerField(default=1, help_text='Πόσες επιλογές επιτρέπονται σε κάθε ψηφοφόρο', verbose_name='Μέγιστες Επιλογές Ανά Ψηφοφόρο'),
        ),
        migrations.AlterField(
            model_name='election',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Κωδικός Πρόσβασης (αν απαιτείται)'),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_date',
            field=models.DateTimeField(verbose_name='Ημερομηνία Έναρξης'),
        ),
        migrations.AlterField(
            model_name='election',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='election',
            name='total_voters',
            field=models.IntegerField(default=0, verbose_name='Σύνολο Ψηφοφόρων'),
        ),
    ]
