# Generated by Django 5.2.1 on 2025-08-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_election_is_public_election_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='visibility',
            field=models.CharField(choices=[('public', 'Δημόσια Εκλογή'), ('private', 'Ιδιωτική Εκλογή')], default='public', max_length=20, verbose_name='Ορατότητα Εκλογής'),
        ),
    ]
